### ISSUE TITLE
No styling out of the box

### ISSUE THREAD

**Issue by e11en** [vitocmpl/ng2-ya-table#1]
Hi I'm testing out your data table for my own project,
but is it correct there is no default styling to the table?
I was kinda hoping that it would look the samen as the demo out-of-the-box.

This is what it looks like when I implement the simple demo.

![capture](https://user-images.githubusercontent.com/855939/27437841-cd35cdfe-5763-11e7-925f-f90aa0774c62.PNG)

**Comment by vitocmpl** [comment]
Yes, you need bootstrap styles (Bootstrap 3) in your own application.

```
<!-- index.html -->
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
```

or [getting-started-with-ng-cli](https://github.com/vitocmpl/ng2-ya-table/blob/master/docs/getting-started/ng-cli.md)

For the future implementations, I'm planning to use a "neutral" style instead bootstrap.
Let me know if this helps you.

**Comment by e11en** [comment]
Works great now, thanks!
