### ISSUE TITLE
Error when getting data dynamically from another component using @Input

### ISSUE THREAD

**Issue by jigneshkhatri** [vitocmpl/ng2-ya-table#7]
I am getting following error when I am getting data dynamically from another component: 

> ERROR TypeError: Cannot read property 'isFirstChange' of undefined
    at Ng2YaTableComponent.ngOnChanges (index.js:256)

I have made separate component for table and using this component in other components. Below is the code of my table component.

Below is my code:
`  

    @Input() data: any[] = [];
    @Input() columns: any[] = [];
    
    constructor() {
     
    }

    public options:any = {
        orderMulti: false,
        className: ['table-striped'],
        language: "en"
    }

    public paging: any = {
        itemsPerPage: 10,
        itemsPerPageOptions: [10, 25, 50, 100],
        maxSize: 5
    }
 
`

`<ng2-ya-table [options]="options" [columns]="columns" [datasource]="data" [paging]="paging">
</ng2-ya-table>
`
I am getting data and columns from another component and they are successfully reaching to this component. What am I missing here?

**Comment by vitocmpl** [comment]
Fixed.
Let me know if it works properly now.
